config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  resources :cards, only: %i[index show]

  resources :games, only: %i[index show new] do
    member do
      get :draw, :play, :reuse, :offer, :score, :store, :undo
      get :unexpand, :expand_left, :expand_right, :expand_upward
      get :switch_player, :to_turn_player, :end_action, :end_turn
      get :increment_action, :action_options, :board_info
      post :conquer
      get :execute
      post :do_execute

      get :test
    end
  end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :playings, -> { order(:ordering) }, dependent: :destroy
  has_many :stocks  , -> { order(:age_id  ) }, dependent: :destroy
  has_many :boards  , -> { order(:color_id) }, dependent: :destroy
  has_many :hands                            , dependent: :destroy
  has_many :influences                       , dependent: :destroy
  has_many :conquests                        , dependent: :destroy
  has_many :players, through: :playings
  belongs_to :turn_player   , class_name: 'Player', foreign_key: :turn_player_id
  belongs_to :current_player, class_name: 'Player', foreign_key: :current_player_id

  attr_accessor :undo_statement, :action_options

  after_create :prepare

  BOARD_COLORS = %w[red green blue yellow purple].map { |n| Color.find_by(name_eng: n) }

  NUM_ACTIONS_PER_TURN = 2

  def human?
    players.any?(&:human?)
  end

  def human_player
    players.detect(&:human?)
  end

  def players_ordered_for_display
    player_showing_hand = human? ? human_player : current_player
    players.rotate(players.index(player_showing_hand)).reverse
  end

  def next_player(player)
    ordering = player.playings.find_by(game: self).ordering
    Playing.where('ordering > ?', ordering).first&.player || players.first
  end

  def other_players_than(player)
    players - [player]
  end

  def current_stock
    age = Age.find_by(level: current_player.max_age_on_boards(self))
    non_empty_stock(age)
  end

  def non_empty_stock(age)
    age = Age.find_by(level: 1) unless age
    stocks.joins(:age).where('ages.level >= ?', age.level).detect { |stock| !stock.empty? }
  end

  def conquered?(target)
    type = "#{target.class}Conquest"
    type_attr = :"#{target.class.name.downcase}"
    conquests.exists?(type: type, type_attr => target)
  end

  def switch_player
    current_ordering = Playing.find_by(player: current_player).ordering
    update!(current_player: Playing.where('ordering > ?', current_ordering).first&.player || players.first)
  end

  def to_turn_player
    update!(current_player: turn_player)
  end

  def end_action
    if num_actions_left > 0
      decrement!(:num_actions_left)
    else
      end_turn
    end
  end

  def end_turn
    player = next_player(turn_player)
    update!(
      turn_player:      player,
      num_actions_left: NUM_ACTIONS_PER_TURN,
      current_player:   player,
    )
  end

  def invite(player)
    ordering = (playings.pluck(:ordering).max&.+ 1) || 0
    playings  .create!(player: player, ordering: ordering)
    hands     .create!(player: player)
    influences.create!(player: player)
    BOARD_COLORS.each do |color|
      boards.create!(player: player, color: color)
    end
  end

  private

    def prepare
      Age.order(:level).each do |age|
        stocks.create!(age: age)
      end
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game            , except: %i[index new]
  before_action :set_action_info     , except: %i[index]
  before_action :clear_undo_statement, except: %i[index show undo]
  before_action :clear_action_options, except: %i[index show]

  KEY_FOR_ACTION_INFO = :action_info

  def index
    redirect_to new_game_path if Game.count.zero?
    @games = Game.all
  end

  def show
    @game_evaluator = GameEvaluator.new(@game, @game.current_player)
  end

  # TODO: Move player adding process to a model or a service.
  def new
    Game.transaction do
      Game.create!(num_players: 2).tap { |game|
        game.invite(Player.find_by(name: 'Hmn'))
        game.invite(Player.find_by(name: 'Cm1'))
        player = game.players.first
        game.update!(turn_player: player, current_player: player)
      }
    end
    redirect_to games_path
  end

  def draw
    age_level = Integer(params[:age_level])
    age = Age.find_by(level: age_level)
    action = PlayerAction::Draw.new(@game, @game.current_player, age)
    perform_action(action)
    redirect_to @game
  end

  def play
    card = Card.find(params[:card_id])
    player = card.card_list(@game).player
    action = PlayerAction::Play.new(@game, player, card)
    perform_action(action)
    redirect_to @game
  end

  def reuse
    card = Card.find(params[:card_id])
    player = card.card_list(@game).player
    action = PlayerAction::Reuse.new(@game, player, card)
    perform_action(action)
    redirect_to @game
  end

  def offer
    card = Card.find(params[:card_id])
    dest = params[:dest].constantize
    action = PlayerAction::Offer.new(@game, card, dest)
    perform_action(action)
    redirect_to @game
  end

  def score
    card = Card.find(params[:card_id])
    player = card.card_list(@game).player
    action = PlayerAction::Score.new(@game, player, card)
    perform_action(action)
    redirect_to @game
  end

  def store
    card = Card.find(params[:card_id])
    player = card.card_list(@game).player
    action = PlayerAction::Store.new(@game, player, card)
    perform_action(action)
    redirect_to @game
  end

  def conquer
    target = params[:target_type].constantize.find(params[:target_id])
    action = PlayerAction::Conquer.new(@game, @game.current_player, target)
    perform_action(action)
    redirect_to @game
  end

  def do_execute

  end

  def test
    ge = GameEvaluator.new(@game, @game.current_player)
    actions = []
    action_sequence = PlayerAction::Sequence.new(ge, actions)
  end

  def end_action
    action = nil
    if @game.uses_ai && @game.turn_player.is_computer && @game.num_actions_left > 0
      player = @game.turn_player
      action = player.choose_action(@game)
      perform_action(action, player.action_options)
    end
    @game.end_action unless action&.conquer_category?
    redirect_to @game
  end

  def undo
    instance_eval(@action_info.undo_statement)
    clear_undo_statement
    redirect_to @game
  end

  def unexpand
    board = Board.find(params[:board_id])
    board.not_expanded!
    redirect_to @game
  end

  def expand_left
    board = Board.find(params[:board_id])
    board.expanded_left!
    redirect_to @game
  end

  def expand_right
    board = Board.find(params[:board_id])
    board.expanded_right!
    redirect_to @game
  end

  def expand_upward
    board = Board.find(params[:board_id])
    board.expanded_upward!
    redirect_to @game
  end

  def switch_player
    @game.switch_player
    redirect_to @game
  end

  def to_turn_player
    @game.to_turn_player
    redirect_to @game
  end

  def increment_action
    @game.increment!(:num_actions_left)
  end

  def action_options
    player = @game.turn_player
    player.choose_action(@game)
    @action_options = player.action_options.sub(/\s+<=\s+\d+\z/, '')
  end

  def board_info
    @player = @game.current_player
    @game_evaluator = GameEvaluator.new(@game, @player)
  end

  private

    def set_game
      if Game.exists?(params[:id])
        @game = Game.find(params[:id])
      else
        redirect_to games_path
      end
    end

    def set_action_info
      @action_info = ActionInfo.new(session[KEY_FOR_ACTION_INFO])
      clear_action_info(:is_executing, :action_targets, :action_message)
    end

    def perform_action(action, action_options = nil)
      targets = action.perform
      session[KEY_FOR_ACTION_INFO] = ActionInfo.new.tap { |ai|
        ai.is_executing = action.execute?
        ai.action_targets = targets
        ai.action_options = action_options
        ai.action_message = action.message_after
        ai.undo_statement = action.undo_statement
      }
    end

    def clear_undo_statement
      clear_action_info(:undo_statement)
    end

    def clear_action_options
      clear_action_info(:action_options)
    end

    def clear_action_info(*attr_names)
      session[KEY_FOR_ACTION_INFO] = @action_info.dup_cleared(*attr_names)
    end
end

app/helpers/games_helper.rb
module GamesHelper

  def age_conquests(player)
    player.conquests_for(@game).find_all(&:age?)
      .map(&:age).map(&:level).join(' ')
  end

  def category_conquests(player)
    player.conquests_for(@game).find_all(&:category?)
      .map(&:category).map(&:name).map(&:first).join(' ')
  end

  def action_options_display(action_options)
    return nil unless action_options
    action_options.split(/\s+/).map { |option|
      if option =~ /(\d+)\)\z/
        weight = Integer(Regexp.last_match(1))
        if weight >= 200
          "<b>#{option}</b>"
        elsif weight.zero?
          "<strike>#{option}</strike>"
        else
          option
        end
      else
        option
      end
    }.join(' ').html_safe
  end
end

app/views/games/action_options.js.erb
$('#action_options').html(
  "<%= j action_options_display(@action_options) %>"
);

app/views/games/board_info.js.erb
<%
  boards = @player.boards_for(@game).map { |board|
    board.tap { |b| b.shows_info = true }
  }
-%>

$('div.board.current div.board_card_piles')
  .children('div.board_card_pile')
    .remove()
  .end()
  .html("<%= j render boards %>")
  ;

app/views/games/do_execute.js.erb
$('#action_message').text('ajax do_execute response');

app/views/games/increment_action.js.erb
$('span#num_actions_left').text(<%= @game.num_actions_left %>);

app/views/games/index.html.erb
<table id="game_list">
  <thead>
    <tr>
      <th>ID</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th>人数</th>
      <th>AI</th>
      <th>説明</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| -%>
      <tr>
        <td class="numeric"><%= link_to game.id, game %></td>
        <td><%= game.created_at.localtime %></td>
        <td><%= game.updated_at.localtime %></td>
        <td class="numeric"><%= game.num_players %></td>
        <td><%= game.uses_ai ? '使用' : '未使用' %></td>
        <td><%= game.remark %></td>
      </tr>
    <% end -%>
  </tbody>
</table>

<div style="margin-top: 10px;">
  <%= link_to 'New', new_game_path %>
</div>

app/views/games/show.html.erb
<% players_ordered_for_display = @game.players_ordered_for_display -%>

<% if @action_info.executing? -%>
  <div class="only_a_flag" id="flag_for_executing" hidden
       data-game_id="<%= @game.id %>"
       data-card="<%= @action_info.target_cards.first.to_s %>"
       >
  </div>
<% end -%>

<div class="game_area">
  <div id="screen_top_area">
    <div id="link_to_root">
      <%= link_to '^', games_path %>
    </div>
    <div class="stocks">
      <% @game.stocks.each do |stock| -%>
        <div class="stock">
          <%= render stock %>
        </div>
      <% end -%>
    </div>
    <% if @game.current_stock -%>
      <div class="stock current">
        <%= render @game.current_stock %>
      </div>
    <% end -%>
    <div id="link_to_cards_index">
      <%= link_to '□', cards_path, target: '_blank' %>
    </div>
  </div>
  <div class="boards">
    <% players_ordered_for_display.each do |player| -%>
      <% is_current = player == @game.current_player
         is_turn    = player == @game.turn_player
         influence_cards = player.influence_for(@game).cards -%>
      <div class="board_and_influence">
        <div class="board <%= is_turn ? '' : 'non_turn' %>">
          <div class="board_scores">
            <div class="board_owner">
              <span class="player_name <%= is_turn ? 'turn' : '' %>">
                <%= "[#{player}]" %>
              </span>
              <span class="max_age_on_boards">
                <%= player.max_age_on_boards(@game) %>
              </span>
              <% if is_current -%>
                <span class="button_to_show_board_info">
                  <%= link_to '!', board_info_game_path(@game), remote: true %>
                </span>
              <% end -%>
            </div>
            <table class="resource_counts">
              <% Resource.all.each do |resource| -%>
                <% count = player.resource_counts(@game)[resource] || 0 -%>
                <tr>
                  <td class="<%= color_class(resource) %>"><%= resource %></td>
                  <td class="numeric"><%= count %></td>
                </tr>
              <% end -%>
            </table>
            <div class="influences">
              <div>
                <span class="show_influence_cards">
                  <%= "[影響] #{player.influence_point(@game)} (#{influence_cards.size})" %>
                </span>
              </div>
              <div>
                <%= player.influence_for(@game).cards.map(&:age).map(&:level).sort.join(' ') %>
              </div>
            </div>
            <div class="player_conquests">
              <div>[制覇]</div>
              <div><%=      age_conquests(player) %></div>
              <div><%= category_conquests(player) %></div>
            </div>
          </div>
          <div class="board_card_piles">
            <%= render player.boards_for(@game) %>
          </div>
        </div>
        <div class="influence_cards" hidden>
          <% influence_cards.each do |card| -%>
            <div class="influence_card">
              <%= render card %>
            </div>
          <% end -%>
        </div>
      </div>
    <% end -%>
  </div>
  <div class="hands">
    <% players_ordered_for_display.each do |player| -%>
      <% is_at_bottom = player == players_ordered_for_display.last
         is_turn      = player == @game.turn_player
         hand_cards   = player.cards_in_hand(@game) -%>
      <div class="hand">
        <div class="hand_cards_and_actions">
          <div class="hand_player">
            <span class="show_hand player_name <%= is_turn ? 'turn' : '' %>">
              <%= "[#{player}](#{hand_cards.size})" %>
            </span>
            <% if is_at_bottom -%>
              <span id="action_message"><%= @action_info.action_message %></span>
            <% end -%>
          </div>
          <div class="hand_cards <%= is_turn ? '' : 'non_turn' %>" <%= is_at_bottom ? '' : 'hidden' %>>
            <% hand_cards.each do |card| -%>
              <div class="hand_card">
                <%= render card %>
              </div>
            <% end -%>
            <% if is_at_bottom -%>
              <div class="open_area">
                <% (open_cards = []).each do |card| -%>
                  <div class="open_card">
                    <%= render card %>
                  </div>
                <% end -%>
              </div>
            <% end -%>
          </div>
          <% if (is_turn || @game.human?) && is_at_bottom -%>
            <div class="hand_actions">
              <%= button_to '=>', end_action_game_path(@game), method: :get %>
              (<span id="num_actions_left"><%= @game.num_actions_left %></span>&nbsp;left)&nbsp;
              <%= button_to '+', increment_action_game_path(@game), method: :get, remote: true,
                    disabled: @game.num_actions_left >= 2 %>
              <%= button_to 'undo', undo_game_path(@game), method: :get, id: 'undo_button',
                    disabled: !@action_info.undo_statement %>
              <%= link_to '<o>', action_options_game_path(@game), method: :get, remote: true,
                    id: 'action_options_link' %>
              <span id="clear_action_options">[c]</span>
            </div>
          <% end -%>
        </div>
      </div>
    <% end -%>
  </div>
  <div class="actions_and_conquests">
    <div class="game_actions">
      <div class="game_links">
        <span id="switch_player">
          <%= link_to '->', switch_player_game_path(@game)  %>
        </span>
        <span id="to_turn_player">
          <%= link_to '^', to_turn_player_game_path(@game)  %>
        </span>
      </div>
      <div class="game_assistants">
        <div id= "game_assisting_command_result"></div>
        <%= text_field_tag :command, nil, id: 'game_assisting_command_text' %>
        <%= button_tag '実行', type: :button, id: 'game_assisting_command_submit' %>
      </div>
    </div>
    <div class="conquests">
      <span id="toggle_conquests">[+]</span>
      <div>
        <div>
          <%= @action_info.undo_statement %>
        </div>
        <div id="action_options">
          <%= action_options_display(@action_info.action_options) %>
        </div>
      </div>
      <div class="button_area" hidden>
        <div class="age_conquests">
          <% Age.order(:level).each do |age| -%>
            <div class="age_conquest">
              <%= button_to age, conquer_game_path(@game, target_type: :Age, target_id: age),
                    disabled: @game.conquered?(age) %>
            </div>
          <% end -%>
        </div>
        <table class="category_conquests">
          <% Category.all.each do |category| -%>
            <tr>
              <td class="col1">
                <%= button_to category.name,
                      conquer_game_path(@game, target_type: :Category, target_id: category),
                      disabled: @game.conquered?(category)%>
              </td>
              <td class="col2">
                <%= category.condition %>
              </td>
              <td class="col3">
                <%= category.note %>
              </td>
            </tr>
          <% end -%>
        </table>
      </div>
    </div>
  </div>
</div>