config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  resources :cards, only: %i[index show]

  resources :games, only: %i[index show new] do
    member do
      get :draw, :play, :reuse, :offer, :score, :store, :undo
      get :unexpand, :expand_left, :expand_right, :expand_upward
      get :switch_player, :to_turn_player, :end_action, :end_turn
      get :increment_action, :action_options, :board_info
      post :conquer
      get :execute
      post :do_execute

      get :test
    end
  end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :age
  belongs_to :color
  has_many :effects, -> { order(:id) }, class_name: 'CardEffect'
  has_many :card_resources
  has_many :resources, through: :card_resources
  has_many :card_list_items
  has_many :card_lists, through: :card_list_items

  POS_LT = 'LT'
  POS_LB = 'LB'
  POS_CB = 'CB'
  POS_RB = 'RB'

  POSITIONS = [POS_LT, POS_LB, POS_CB, POS_RB]
  POSITIONS_AT_BOTTOM = POSITIONS[1, 3]

  LEFT   = [POS_LT, POS_LB]
  RIGHT  = [POS_RB]
  BOTTOM = POSITIONS_AT_BOTTOM

  def resource_at(position_abbr)
    h_resources_by_position[position_abbr]
  end

  def resources_at(card_side_for_position_abbrs)
    return [] unless card_side_for_position_abbrs
    card_side_for_position_abbrs.map { |pos| resource_at(pos) }.compact
  end

  def has_resource?(resource_name)
    resources.include?(Resource.find_by(name: resource_name))
  end

  def card_list(game)
    card_lists.find_by(game: game)
  end

  def prev
    self.class.where('id < ?', id).order(id: :desc).first || self
  end

  def next
    self.class.where('id > ?', id).order(id: :asc ).first || self
  end

  def forcing?
    (effects.size == 1 && !effects.first.is_for_all) \
      || (effects.size == 2 && !effects.first.is_for_all && effects.last.conditional_on_effect_above?)
  end

  def effect_factor_sum(game_evaluator)
    effects.to_a.sum { |effect| effect.effect_factor(game_evaluator) }
  end

  def eql?(other)
    other.is_a?(self.class) && id == other.id
  end

  def hash
    id.hash
  end

  def to_s
    "[#{age.level}]#{title}"
  end

  private

    def h_resources_by_position
      @h_resources_by_position ||= \
        card_resources.joins(:resource, :position)
        .select('resource_positions.abbr', 'resources.name_eng').map { |r|
          attrs = r.attributes
          [attrs['abbr'], Resource.send(attrs['name_eng'].downcase)]
        }.to_h
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
    @game = Game.last
  end
end

app/helpers/cards_helper.rb
module CardsHelper

  def color_class(model, options = {})
    return '' unless model && (@uses_color || options[:force])
    model.color.name_eng
  end

  def card_effect_in_span(effect)
    content_tag :span do
      concat (
        content_tag :span, effect.resource, class: color_class(effect.resource)
      )
      concat "#{effect.is_for_all ? '+' : '>'} #{effect.content}"
    end
  end

  def card_effects_display(card)
    safe_join(card.effects.map { |e| card_effect_in_span(e) }, '<br>'.html_safe)
  end

  def card_resource_in_div(card, pos)
    model = card.resource_at(pos) || card.age.level
    color = model.is_a?(Integer) ? 'age' : color_class(model)
    content_tag :div, class: 'card_resource' do
      content_tag :span, class: color do
        content_tag :span, model, class: color
      end
    end
  end
end

app/views/cards/_bottom.html.erb
<div class="card_bottom">
  <% Card::POSITIONS_AT_BOTTOM.each do |pos| -%>
    <%= card_resource_in_div(card, pos) %>
  <% end -%>
</div>

app/views/cards/_card.html.erb
<div class="card <%= @action_info&.target_in_use?(card) ? 'in_use' : '' %>">
  <div class="card_top">
    <%= card_resource_in_div(card, Card::POS_LT) %>
    <% unless @uses_color -%>
      <div class="color_mark">
        <%= card.color.name_eng.first.upcase %>
      </div>
    <% end -%>
    <div class="card_title <%= color_class(card) %>">
      <%= card.title %>
    </div>
  </div>
  <div class="card_effect">
    <%= card_effects_display(card) %>
  </div>
  <div class="card_bottom">
    <% Card::POSITIONS_AT_BOTTOM.each do |pos| -%>
      <%= card_resource_in_div(card, pos) %>
    <% end -%>
  </div>
  <% if @game -%>
    <div class="card_actions" hidden>
      <% case card_list = card.card_list(@game) -%>
      <% when Hand -%>
        <div class="card_actions_row">
          <div class="card_action">
            <%= link_to '場', play_game_path(@game, card_id: card) %>
          </div>
          <div class="card_action">
            <%= link_to '再生', reuse_game_path(@game, card_id: card) %>
          </div>
          <div class="card_action">
            <%= link_to '得点', score_game_path(@game, card_id: card) %>
          </div>
          <div class="card_action">
            <%= link_to '保存', store_game_path(@game, card_id: card) %>
          </div>
        </div>
        <div class="card_actions_row">
          <div class="card_action">
            <%= link_to '手札に譲', offer_game_path(@game, card_id: card, dest: Hand) %>
          </div>
          <div class="card_action">
            <%= link_to '領域に譲', offer_game_path(@game, card_id: card, dest: Board) %>
          </div>
        </div>
        <div class="card_actions_row">
          <div class="card_action">
            <%= link_to '影響に譲', offer_game_path(@game, card_id: card, dest: Influence) %>
          </div>
        </div>
      <% when Board -%>
        <div class="card_actions_row">
          <% if card_list.cards.size >= 2 -%>
            <div class="card_action">
              <% if card_list.expanded_left? -%>
                <%= link_to '戻', unexpand_game_path(@game, board_id: card_list) %>
              <% else -%>
                <%= link_to '左', expand_left_game_path(@game, board_id: card_list) %>
              <% end -%>
            </div>
            <div class="card_action">
              <% if card_list.expanded_right? -%>
                <%= link_to '戻', unexpand_game_path(@game, board_id: card_list) %>
              <% else -%>
                <%= link_to '右', expand_right_game_path(@game, board_id: card_list) %>
              <% end -%>
            </div>
            <div class="card_action">
              <% if card_list.expanded_upward? -%>
                <%= link_to '戻', unexpand_game_path(@game, board_id: card_list) %>
              <% else -%>
                <%= link_to '上', expand_upward_game_path(@game, board_id: card_list) %>
              <% end -%>
            </div>
          <% end -%>
          <div class="card_action">
            <%= link_to '再生', reuse_game_path(@game, card_id: card) %>
          </div>
          <div class="card_action">
            <%= link_to '得点', score_game_path(@game, card_id: card) %>
          </div>
        </div>
        <div class="card_actions_row">
          <div class="card_action">
            <%= link_to '手札に譲', offer_game_path(@game, card_id: card, dest: Hand) %>
          </div>
          <div class="card_action">
            <%= link_to '領域に譲', offer_game_path(@game, card_id: card, dest: Board) %>
          </div>
        </div>
      <% when Influence -%>
        <div class="card_actions_row">
          <div class="card_action">
            <%= link_to '場', play_game_path(@game, card_id: card) %>
          </div>
          <div class="card_action">
            <%= link_to '再生', reuse_game_path(@game, card_id: card) %>
          </div>
        </div>
        <div class="card_actions_row">
          <div class="card_action">
            <%= link_to '手札に譲', offer_game_path(@game, card_id: card, dest: Hand) %>
          </div>
          <div class="card_action">
            <%= link_to '領域に譲', offer_game_path(@game, card_id: card, dest: Board) %>
          </div>
        </div>
      <% end -%>
    </div>
  <% end -%>
</div>

app/views/cards/_left.html.erb
<div class="card_side_top">
  <%= card_resource_in_div(card, Card::POS_LT) %>
</div>
<div class="card_side_middle">
</div>
<div class="card_side_top">
  <%= card_resource_in_div(card, Card::POS_LB) %>
</div>

app/views/cards/_right.html.erb
<div class="card_side_top">
</div>
<div class="card_side_middle">
</div>
<div class="card_side_top">
  <%= card_resource_in_div(card, Card::POS_RB) %>
</div>

app/views/cards/index.html.erb
<table id="card_list" class="table_base">
  <% @cards.each do |card| -%>
    <tr>
      <td class="<%= color_class(card) %>">
        <%= card.age.level %>
      </td>
      <td class="card_title">
        <%= link_to card.title, card %>
      </td>
      <% Card::POSITIONS.each do |pos| -%>
        <% resource = card.resource_at(pos) %>
        <td class="<%= color_class(resource) %>">
          <%= resource %>
        </td>
      <% end -%>
      <td><%= card_effects_display(card) %></td>
    </tr>
  <% end -%>
</table>

app/views/cards/show.html.erb
<div id="card_navi">
  <span><%= "#{@card.id.to_s.rjust(3, '0')}/#{Card.count.to_s.rjust(3, '0')}" %></span>
  <%= link_to '<', card_path(@card.prev) %>
  <%= link_to '^', cards_path %>
  <%= link_to '>', card_path(@card.next) %>
</div>

<div class="card_info">
  <%= render @card %>

  <div class="effects">
    <table>
      <tr>
        <td><%= "==> 必要条件 <==" %></td>
      </tr>
      <% @card.effects.each do |effect| -%>
        <tr>
          <td><%= effect.necessary_condition %></td>
        </tr>
        <% @game.players.each do |player| -%>
          <% ge = GameEvaluator.new(@game, player) -%>
          <tr>
            <td><%= "#{player}: #{effect.executable?(ge)}" %></td>
          </tr>
        <% end -%>
      <% end -%>
      <tr>
        <td><%= "==> 評価関数 <==" %></td>
      </tr>
      <% @card.effects.each do |effect| -%>
        <tr>
          <td><%= effect.evaluation_f %></td>
        </tr>
        <% @game.players.each do |player| -%>
          <% ge = GameEvaluator.new(@game, player) -%>
          <tr>
            <td><%= "#{player}: #{effect.effect_factor(ge, assumes_executable = true)}" %></td>
          </tr>
        <% end -%>
      <% end -%>
      <tr>
        <td><%= "==> 実行文 <==" %></td>
      </tr>
      <% @card.effects.each do |effect| -%>
        <% f_action_preparer = effect.action_preparer(@game) -%>
        <% @game.players.each do |player| -%>
          <tr>
            <td><%= "#{player}: #{f_action_preparer.call(player)}" %></td>
          </tr>
        <% end -%>
      <% end -%>
    </table>
  </div>
</div>